📦️ config-assets: packages/config-assets/**/*
📦️ config-browserslist: packages/config-browserslist/**/*
📦️ config-prettier: packages/config-prettier/**/*
📦️ config-stylelint: packages/config-stylelint/**/*
📦️ config-typescript: packages/config-typescript/**/*
📦️ plugin-eslint: packages/plugin-eslint/**/*
📦️ plugin-postcss: packages/plugin-postcss/**/*
👽️ dependency: package.json
🔖 release: packages/**/CHANGELOG.md
🔧 tooling: scripts/*
