👽️ dependency:
  - any: ['**/package*', '**/yarn.lock', '.pnp.*']
📝 documentation:
  - any: ['src/**/*.md', 'docs/**/*']
🔖 release: '**/CHANGELOG.md'
🔧 tooling:
  - any:
      [
        '*',
        '.github/**/*',
        '.vscode/**/*',
        '.yarn*',
        '.yarn/**/*',
        'scripts/**/*',
        '!package*',
        '!yarn.lock',
        '!*.md',
      ]
# Package labels
'📦️ config: assets': 'packages/assets-config/**/*'
'📦️ config: browserslist': 'packages/browserslist-config/**/*'
'📦️ config: prettier': 'packages/prettier-config/**/*'
'📦️ config: stylelint': 'packages/stylelint-config/**/*'
'📦️ config: typescript': 'packages/typescript-config/**/*'
'📦️ plugin: eslint': 'packages/eslint-plugin/**/*'
'📦️ plugin: postcss': 'packages/postcss-plugin/**/*'
