👽️ dependency:
  - any: ['**/package*', '**/yarn.lock', '.pnp.*']
📝 documentation:
  - any: ['src/**/*.md', 'docs/**/*']
🔖 release: '**/CHANGELOG.md'
🔧 tooling:
  - any:
      [
        '*',
        '.github',
        '.vscode',
        '.yarn*',
        '.yarn/**/*',
        'scripts/**/*',
        '!package*',
        '!yarn.lock',
        '!*.md',
      ]
# Package labels
📦️ config-assets: packages/config-assets/**/*
📦️ config-browserslist: packages/config-browserslist/**/*
📦️ config-prettier: packages/config-prettier/**/*
📦️ config-stylelint: packages/config-stylelint/**/*
📦️ config-typescript: packages/config-typescript/**/*
📦️ plugin-eslint: packages/eslint-plugin/**/*
📦️ plugin-postcss: packages/postcss-plugin/**/*
