name: Labeler
on: [pull_request_target]

jobs:
  triage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v2

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BEEFCHIMI_APP_ID }}
          private_key: ${{ secrets.BEEFCHIMI_APP_PRIVATE_KEY }}

      - name: Apply PR labels
        uses: actions/labeler@v3
        with:
          repo-token: ${{ steps.generate-token.outputs.token }}
