name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      - name: Install dependencies and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Create Release Pull Request or Publish to Github Packages
        id: changesets
        uses: changesets/action@v1
        with:
          # Because each package defines both a `publishConfig` and a `repository`,
          # the action should understand which registry to publish to.
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
